# Generated by Django 6.0.4 on 2026-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nin', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('select_product', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('product_name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('payment_method', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.TextField()),
                ('specification', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(max_length=255)),
            ],
        ),
    ]
