# Generated by Django 6.0.4 on 2026-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('stock_date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.TextField()),
                ('specification', models.CharField(max_length=255)),
                ('payment_mode', models.IntegerField()),
            ],
        ),
    ]
