# Generated by Django 6.0.4 on 2026-05-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='payment_mode',
            new_name='payment_method',
        ),
    ]
