# Generated by Django 6.0.4 on 2026-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='payment_mode',
            field=models.CharField(max_length=255),
        ),
    ]
