# Generated by Django 6.0.3 on 2026-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0002_rename_payment_mode_register_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
