# Generated by Django 6.0.3 on 2026-05-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0003_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.CharField(max_length=255),
        ),
    ]
