# Generated by Django 6.0.3 on 2026-05-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0004_alter_stock_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
