# Generated by Django 6.0.3 on 2026-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0005_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
