# Generated by Django 6.0.3 on 2026-05-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareapp', '0006_sale_address_sale_phone_number_sale_product_name2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_name2',
        ),
        migrations.AddField(
            model_name='sale',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='wants_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='within_10km',
            field=models.BooleanField(default=False),
        ),
    ]
